# name: Backend PR Checks

# on: 
  
#   pull_request:
#     branches: [pipeline-cleanup]
#     paths:
#     - 'backend/**'
  
# jobs:

#   build-backend:
#     name: Build Backend Docker
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       packages: write
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1

#       - name: Build and push Backend Docker image
#         uses: docker/build-push-action@v2
#         with:
#           context: ./backend/
#           push: false 
#           tags: backend:latest

#   test-backend:
#     name: Test Backend
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-java@v3
#         with:
#           java-version: '17'
#           distribution: 'adopt'
#       - name: Run the Maven verify phase
#         run: mvn --batch-mode -f backend/ verify