name: Database PR Checks

on: 
  
  pull_request:
    branches: [pipeline-cleanup]
    paths:
    - 'database/**'
  
jobs:

  build-database:
    name: Build-Database
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Database Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./database/
          push: false
          tags: database:latest