name: Cleanup

on:
  pull_request:
    types:
      - closed
    branches:
      - main

env:
  NAME: gfp
  REPONAME: greenfield-template

jobs:
  cleanup-ghcr:
    name: Cleanup ghcr.io
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/ghcr-io-container-cleanup
      - name: Delete old packages
        uses: davahome/ghcr-cleanup@v1
        with:
          token: ${{ secrets.DELETE_PACKAGES_TOKEN }}
          package: ${{ env.REPONAME }}
          owner: orgs/bcgov
          skip_tags: prod,test
